package com.lvjinke.bit.Generics;

public enum  Watercolors {
    ZNIC,LEMON_YELLLOW,DEEP_YELLOW,ORANGE,VIOLET,
    ROSE_MADDER,RAW_UMBER,CRIMSON,YELLOW_OCHER,BURNT_SIENNA,
    IVORY_BACLK,PHTHALO_BLUE
}
